ci: gits dev

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,7 +12,9 @@ permissions:
     id-token: write
     actions: write
     attestations: write
-
+env:
+    ACTIONS_RUNNER_DEBUG: true
+    ACTIONS_STEP_DEBUG: true
 jobs:
     integration-testing:
         runs-on: ubuntu-latest
@@ -21,13 +23,14 @@ jobs:
             - uses: actions/setup-go@v4
               with:
                   go-version: stable
+
             - name: Install gotestsum
               run: go install gotest.tools/gotestsum@latest
+
             - name: Install GitHub CLI
               run: |
                   sudo apt-get update
                   sudo apt-get install -y gh
-
 
             - name: Run tests
               run: |
@@ -35,28 +38,48 @@ jobs:
                     --junitfile junit.xml \
                     --jsonfile test-output.json \
                     -- -v ./tests/integration
-            - uses: actions/upload-artifact@v4
-              if: always()
-              with:
-                  name: test-results
-                  path: |
-                      junit.xml
-                      test-output.json
 
-
+#            - uses: actions/upload-artifact@v4
+#              if: always()
+#              with:
+#                  name: test-results
+#                  path: |
+#                      junit.xml
+#                      test-output.json
+#                      integration-status.json
 
             - name: Update Gist with new test results
               if: always()
               env:
                   GIST_ID: ${{ secrets.GIST_ID }}
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              run: |
-                  gh gist edit $GIST_ID -d test-output.json
-                  gh gist edit $GIST_ID -a test-output.json
-                  gh gist edit $GIST_ID -d junit.xml
-                  gh gist edit $GIST_ID -a junit.xml
-                  gh gist edit $GIST_ID -d /integration-status.json
-                  gh gist edit $GIST_ID -a /integration-status.json
+                  GITHUB_TOKEN: ${{ secrets.GIST_PAT_TOKEN }}
+              run: |-
+                  gh auth status
+                     gh gist edit $GIST_ID -a integration-status.json || {
+                      echo "Error code: $?"
+                      gh gist edit $GIST_ID -d integration-status.json
+                      gh gist edit $GIST_ID -a integration-status.json
+                    }
+
+#            - name: Configure Git
+#              run: |
+#                git config --global user.name "github-actions[bot]"
+#                git config --global user.email "github-actions[bot]@users.noreply.github.com"
+#
+#            - name: Update Gist with new test results
+#              if: always()
+#              env:
+#                GIST_ID: ${{ secrets.GIST_ID }}
+#                GH_TOKEN: ${{ secrets.GIST_PAT_TOKEN }} # Changed to use PAT
+#              run: |-
+#                gh auth status
+#                touch gist.txt
+#                echo "HI" > gist.txt
+#                gh gist edit $GIST_ID -a gist.txt || {
+#                  echo "Error code: $?"
+#                  gh gist list
+#                }
+
 
 
             - name: Publish Test Results
